# Generated by Django 5.1.2 on 2024-10-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='observations_day_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='observations_day_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='real_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='real_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
